@startuml

abstract class Employee {
    - firstName : String
    - lastName : String
    - socialSecurityNumber : String
    --
    + Employee(firstName : String, lastName : String, socialSecurityNumber : String)
    ..
    + getFirstName() : String
    + getLastName() : String
    + getSocialSecurityNumber() : String
    + setFirstName(firstName : String) : void
    + setLastName(lastName : String) : void
    + setSocialSecurityNumber(socialSecurityNumber : String) : void
    + printDetails() : void
}

class SalariedEmployee {
    - weeklySalary : double
    --
    + SalariedEmployee(firstName : String, lastName : String, socialSecurityNumber : String, weeklySalary : double)
    ..
    + getWeeklySalary() : double
    + setWeeklySalary(weeklySalary : double) : void
    + printDetails() : void
}

class HourlyEmployee {
    - wage : double
    - workHours : double
    --
    + HourlyEmployee(firstName : String, lastName : String, socialSecurityNumber : String, wage : double, workHours : double)
    ..
    + getWage() : double
    + getWorkHours() : double
    + setWage(wage : double) : void
    + setWorkHours(workHours : double) : void
    + printDetails() : void
}

class CommissionEmployee {
    - commissionRate : double
    - grossSales : double
    --
    + CommissionEmployee(firstName : String, lastName : String, socialSecurityNumber : String, commissionRate : double, grossSales : double)
    ..
    + getCommissionRate() : double
    + getGrossSales() : double
    + setCommissionRate(commissionRate : double) : void
    + setGrossSales(grossSales : double) : void
    + printDetails() : void
}

class BaseEmployee {
    - baseSalary : double
    --
    + BaseEmployee(firstName : String, lastName : String, socialSecurityNumber : String, baseSalary : double)
    ..
    + getBaseSalary() : double
    + setBaseSalary(baseSalary : double) : void
    + printDetails() : void
}

' Hierarchy
Employee <|-- SalariedEmployee
Employee <|-- HourlyEmployee
Employee <|-- CommissionEmployee
Employee <|-- BaseEmployee

@enduml
